spring:
  application:
    name: boards
  datasource:
    url: jdbc:mysql://mymysql:3306/boards?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${username}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: create
server:
  port: 8080