spring:
  application:
    name: boards
  datasource:
#    url: jdbc:h2:mem:test
    url: jdbc:mysql://34.28.130.130:3306/boards?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
server:
  port: 8080