spring:
  application:
    name: boards
  datasource:
#    url: jdbc:h2:mem:test
    url: jdbc:mysql://localhost:3306/boards?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: test
    password: 0000
  jpa:
    hibernate:
      ddl-auto: create
server:
  port: 8080