spring:
  application:
    name: boards
  datasource:
    url: jdbc:mysql://localhost:3306/boards?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
server:
  port: 8080